# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.3 on 2017-08-12 12:10
from __future__ import unicode_literals

from django.db import migrations, models
=======
# Generated by Django 1.11.3 on 2017-08-11 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import member.models
>>>>>>> master
import utils.fields.custom_imagefields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
<<<<<<< HEAD
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=40, null=True, unique=True, verbose_name='nickname')),
=======
                ('user_type', models.CharField(choices=[('django', 'Django'), ('facebook', 'Facebook')], default='django', max_length=1)),
                ('username', models.CharField(max_length=100, null=True, unique=True, verbose_name='email address')),
                ('nickname', models.CharField(max_length=40, null=True, verbose_name='nickname')),
>>>>>>> master
                ('img_profile', utils.fields.custom_imagefields.CustomImageField(blank=True, default='member/basic_profile.png', upload_to='member')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('objects_fb', member.models.FacebookUserManager()),
            ],
        ),
    ]
