# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='nickname',
            new_name='username',
        ),
    ]
