# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 07:06
from __future__ import unicode_literals

from django.db import migrations
import utils.fields.custom_imagefields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='img_profile',
            field=utils.fields.custom_imagefields.CustomImageField(blank=True, default='member/basic_profile.png', upload_to='member'),
        ),
    ]
