# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170812_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
