# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 16:02
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='weather',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
