# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_shared_list',
            field=models.BooleanField(default=False),
        ),
    ]
