# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together=set([('user', 'name_playlist', 'id')]),
        ),
    ]
