# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
