# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170803_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='file_music',
        ),
        migrations.AddField(
            model_name='music',
            name='source_music',
            field=models.CharField(default='none', max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='music',
            name='img_music',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
