# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170808_0102'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='weather',
            managers=[
            ],
        ),
    ]
