# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20170804_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='source_music',
            field=models.CharField(max_length=256),
        ),
    ]
