# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20170804_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='name_singer',
            new_name='name_artist',
        ),
        migrations.RemoveField(
            model_name='music',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='music',
            name='name_author',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='music',
            name='cloudy',
            field=models.PositiveIntegerField(default=0, verbose_name='흐림'),
        ),
        migrations.AlterField(
            model_name='music',
            name='foggy',
            field=models.PositiveIntegerField(default=0, verbose_name='안개'),
        ),
        migrations.AlterField(
            model_name='music',
            name='rainy',
            field=models.PositiveIntegerField(default=0, verbose_name='비'),
        ),
        migrations.AlterField(
            model_name='music',
            name='snowy',
            field=models.PositiveIntegerField(default=0, verbose_name='눈'),
        ),
        migrations.AlterField(
            model_name='music',
            name='sunny',
            field=models.PositiveIntegerField(default=0, verbose_name='맑음'),
        ),
    ]
