# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20170805_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='time_music',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
