# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20170808_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='lyrics',
            field=models.TextField(blank=True),
        ),
    ]
